#!/usr/bin/env julia

#=
A solution to a programming assignment for the Bioinformatics Algorithms (Part 1) on Coursera.
Textbook: Bioinformatics Algorithms: An Active-Learning Approach
Authors: Phillip Compeau & Pavel Pevzner

=#

# -----------------------------
# DNA Codon Table (DNA → Protein)
# -----------------------------
const DNA_CODON_TABLE = Dict(
    "TTT"=>"F", "TTC"=>"F", "TTA"=>"L", "TTG"=>"L",
    "CTT"=>"L", "CTC"=>"L", "CTA"=>"L", "CTG"=>"L",
    "ATT"=>"I", "ATC"=>"I", "ATA"=>"I", "ATG"=>"M",
    "GTT"=>"V", "GTC"=>"V", "GTA"=>"V", "GTG"=>"V",

    "TCT"=>"S", "TCC"=>"S", "TCA"=>"S", "TCG"=>"S",
    "CCT"=>"P", "CCC"=>"P", "CCA"=>"P", "CCG"=>"P",
    "ACT"=>"T", "ACC"=>"T", "ACA"=>"T", "ACG"=>"T",
    "GCT"=>"A", "GCC"=>"A", "GCA"=>"A", "GCG"=>"A",

    "TAT"=>"Y", "TAC"=>"Y", "TAA"=>"Stop", "TAG"=>"Stop",
    "CAT"=>"H", "CAC"=>"H", "CAA"=>"Q", "CAG"=>"Q",
    "AAT"=>"N", "AAC"=>"N", "AAA"=>"K", "AAG"=>"K",
    "GAT"=>"D", "GAC"=>"D", "GAA"=>"E", "GAG"=>"E",

    "TGT"=>"C", "TGC"=>"C", "TGA"=>"Stop", "TGG"=>"W",
    "CGT"=>"R", "CGC"=>"R", "CGA"=>"R", "CGG"=>"R",
    "AGT"=>"S", "AGC"=>"S", "AGA"=>"R", "AGG"=>"R",
    "GGT"=>"G", "GGC"=>"G", "GGA"=>"G", "GGG"=>"G"
)

# -----------------------------
# Reverse Complement
# -----------------------------
const COMPLEMENT = Dict('A'=>'T', 'T'=>'A', 'C'=>'G', 'G'=>'C')

reverse_complement(dna::AbstractString) = join(COMPLEMENT[c] for c in reverse(dna))

# -----------------------------
# DNA Slice Translation
# -----------------------------
function translate_dna(dna_seq::AbstractString)
    protein = IOBuffer()
    for i in 1:3:length(dna_seq)-2
        codon = dna_seq[i:i+2]
        aa = DNA_CODON_TABLE[codon]
        if aa == "Stop"
            break
        end
        print(protein, aa)
    end
    return String(take!(protein))
end

# -----------------------------
# Read Input
# -----------------------------
dna= "CTAGTTTGTGAGAGTCCGAATATGTGCCAATGAATAAAATAGGAAAGTGTCACGCGATTTCAACAGTTATAACCTAACCCGACGTCATGTGGTAACCCAGGTCTTGCCCACGTGATCAGAGTGGTGTCGAGACCAGGCGGTGGCCTAGGGCTCACTCCTTAAATGGCCATAAACATGTAGATAGGCAAGAGACTGATGCTAATTAACGTAGACGTCACCGCTCTGAGGGCTATATCTGACACTACAACCGAGACGCTGCATTCTGCGTCGCTGTAAATGTCTGTTAACAATCTTATGTGAAGTCAGGGCGGCGCCCGCCTCACCCCTAGGACTTGGTCTTTCTATGTATACTATGAAGCGACTTAGATCGGGTGGGTGAGCGTCGCTATGTCTCCGTGAGTTGGGGCTCAACTTGTGCGTTCCAATTCCGGTGAAGCATCAGGTACTACATAGGCAATCAGGGTGGGACGCCTGTATCGAGACACAGGTCTGGATCTGCTTAGGGTCTCGTGCGTCTGAAGGAGATGTAATGGCCGCTGTAAGACCGTGCCCCCATAACGTACCCTAGCTGGACGCGCGCAAGGGTCAACAGGTGCACACAACGTTGTAAACTACGTGTCTAAATGGGCGCCACCTCGAAGAAAGTTCATAGTGGCGTACGAGACCATAATTTCATAAAATTCCCAGTATGCGTCATCTACCCCCAGTCTATCCAAATGTACGAGTAGGTGAATGGTGTTAACAGATCTGGTGCCAGAGAGGACCAACAGGCCGCAGATGGAATGCGACTCTGAATCGCAATCGGTTCGTAATCACTCCATCACCACTATGCCCCCCTTCGCGAAATGGAATGGAAGTCTAGTACGGTGGTGCGAGGATGTCCCCCGGGAGTTTTGCACCACCCAAAAACGGAGTAGCCCTCCTATGGCAAGGTAAGGCGTTGCTGATGAATATACCTTTGTGCGTCAAGGTAGTTTAGGAACCATATAGATTAATGCATGAAAGCTGATGTGCTGTCGCGAAGTCACTAGCGAGTACTCACGCGGAAACAGTGGATTCCTTGGGAAAGTTACACAATGCGCGTCTGAGGTATGGCGTATAGGGTCGGACCGTTGTGCATCCGTCTCCTATGGTGTCGTCCCTGCTTAACCCAAGCGCGTGGGTTCGGCCATCCGGAGATTTACCCCACCGGCCGTATGAGTTTCGAGTTAGATCTCTACCATGGGCCCCAATGTTTTGTTAATGTATCACCTAGGGTGCTCCTTGCGGTTGACCCAGTTCTCGAATCACGGGTCATCTAGGGTATCGCCGGGCCGAAATACGGAGGCCTAGAACTCGTTAATAGACCCTGTGTGTTGTGTCAGTCGAGCGCCCCATACCAGAGTACGCGCAGTACATACACTCCGCGTGTGAGCGACGCCCCGCACACAACGTGAGGGTATATCTCAGTGAGTTCCTAACAGAATTCATGCCAAGGAGTCCATGTACACTCATCTTCAATCTCCGCATATGGAGGCTTTCGGGTTCCCACAAAGCCGAAACAAACGTGAAGAACGGTGGTCGTTCAAGGTGACCAATTCCCCCTGCCGCCTAATTCAGTCGTGGCAAGAATCGTTGGACGCCGATCAAGAGTCTGCGTTACGATGTGGTCTTCTCGAACCATTGGAATGGGATACTAAGAGGTAGGGCGCGATTCTTAGCTTGTCCAACGAGACTGAGCTCTGGAAACCACAAAGTATATAGCGGTGATTATGAGATTAACTCCAATTGTGCGCATCATGACCCGGAAATAGTGGCCATGTTGTTACCTTTTAGGATTGTTCCGGTCACGGCAATTGACACTGTTTCATCCATGTTTCTCAATGGGCATGGGCCACAGTGTTTCGTTAATGTCTCATGTCCGTTGATTTTACCGGCAGCCGCATTTGATTCGATAATCTGTCATTGACCAGAGATTTGCACGAGTCGGCTTAGAAGTGGAATGCCACACTACGGAACATGGAGAGAAAGCCGGCTCGTAGGCGTTGTTATGTACGCCGCGTGTTAAAAGTTAGTTCGGGACTGACCCCGGAGAATTGTTATGGAGACTCATTTTTCTAGCGTAAACACGTATTTATTGGTGGGACTATGACCCATCCCCAGTGTAGTGACTGCAAGGGCATTCCATCATCCAGAGGATCACATCCACCCAAGAGAACCCTAGGTATAGCGTCACATTAACAAAGCATTGCGGTCCATGATTTTATGGTAGCGGGAGGAGGGATACGATTTTCCAGCCCTCCAACGAGATCCTGCGCTTTCAGGGGGGTCATCTTTCTTTTATACAACTTTCAGGTGGTCCCATGTGCCCATCTTGCCAACCGCTCTGACTTACTGCGGACGCCCAAATTAACTTGGTGCGGGCTAGCTATATCTCGTCATTAAGCGCTGGAACGTGGTATATTAGTGGCGCAGTATAGACCAGCTACTCGGGCGGAAGGCGTGAATCAATACCTGTGTTCGCAAAGAGCGGAGCCCGGGTCTCCGAACCGGCAACGAAAGCATGAATGAGATTTTCTGGCGGGGATCTCTCCAGTAGCCCCCCCCAGGTGGAAGAAAATCATAATTGATAATAGTGATCTGTCAGACCGCATCTAAGAACAGGGCTACCGGATCCCCGCGGCCGACTTGTCCTAAATACTTGTAAAGTAGGTTCGGCTACATTACCTTGGCACTCCACCAAGGAATCAAGCTACTGCCCCAAGCCCGTTCCCTCTGCGGGCGCGGCGTAGTCGGCGATACCTGACAGTTGTTCAATAAGAGAGTGCTTAACCCACCCTGCTCAGGACTTAGACCGCACTACATATGTTATATCCACGTTTCAATTGCTAGTTGGTCTAGGGTGGTTATGTCTAACTCAGCTCAAACCTCTCCTTATTGTATGATTAGTAATAGCCCCACTTCACCGGGTAGGGGGAGTCAGCGCGCTTGCGAGATGCAGATTGCGTACTCTCCGGCCGATTAGTACGCTCGCGTTGAGAACTGTCGCAGCTGTCGTCTCCTGCGGGCGGTTCTATACCTTTTAACGAGGAATTATTCCTGAACATTCATGTAATGGCCTTCGACATGGGCCACAGTGTTTCGTAAACGTCGAACACACATAGAGCCCACGTCTACTTGTCATATCTCAAGAAGCACAACGGGTATATCGAAAGACAGAATTCTAGGTGATAAGAGTATAATCAAGTTGACATCTTGCGCGACTTCTACGTTCATGCCGCTCCTAAAGAGGACTAGTGCAAACGAGTACGAATATGCTATCCATGCCCGCCCTGAGCCCCTTCGGCACCACATTGACAAAGCACTGGGGCCCGTGAGTGGTATAAAAGTTATCCGCTGTATACCAGGGCGTGGTGGCTGTTAGCCTGGAGAATAAATAAGTTGACTCATTACGAAATAAATAGGTCTGTGATCACCTGGCACCTACTGAGAATCCTCCCAGCTCAAAGAGCCGAAAGGAGCCAACCCGGGCTTACCAGATGTCCTGGAACCAGTTGAATGCGATCGGAGACTGGCTCCTCCGACGAGTGACGCTCATGGACCGCAATGCTTTGTGAATGTTCAGGCATAGTTGTTCGACATTAACATTTGAGATGGGTCACCCATAGTTAGGCGTTAATATTCTGTGGCACGGCCCTCAATGTTTCGTTAACGTATATTCTGAAAGACCCCAAGGCTTGGCATTTACTACCAACTCCCCAGGTGGAGTGGGAGTCTACTGCCCGAAGCCAGCACTTTCTCCAAGAACATAAATGTTTGAGGCGGAAAGCTCGGCGTCTTCTCACTCACTGCATGACCCAGCCAACATTCACGAAGCACTCACGGACCCCAGTGCTTTGTAAACGTATTTCAATCATATTTTTTTTTATCTTGTTAATACCCTCGGTTGAAACCTAGGCCACTGCCGTTCATGCGCCTCTGGCTCACGCTGCTTGTACAGGCTTCAAGAGTTAACGAGCACATTATGGCCGACGACCTTAACAGAATGTGATATCTACGGGCCGAGTGGCACTACATCTCGAGCGGCCGGGTCGGTCTAAAGAGTCAAAGGGTAGATCGACTACATCCTTGCGCGACACCCCGTCTTTGGTGCAATCAAATCTGTAAAATGTTCTTCGGTTCTCGTGTGCATAGTTTGCCCTTGAGGCAGCCAGGCCGCTTGTATGATCCGGCTTTCCTCGGACATATCCATGGACCCCAATGCTTCGTTAACGTACCTTCGGTGGGCGCTGACATACCGTCGTTGTCGTTCGAACTGCGACGAGCGCTCACCTCTCGCAGTGCGGATCTAAAAGTACGCAAACCCTGCGATCCCGTGAGACCCTGACCAAGACGACTCGCCGAGGCGCACCATTATCTTTGTGTCCCTTCGCAGAGGTAGCGAGGACGTTTGAAATCCATGCACCGGTCGGACGATCCGGACCGCCCTCTATCCGGCCTTCATGGACCACAATGTTTTGTTAACGTCGATAAATCTTAAAGGACTAATATCGCATTTCTGATCATGCCCGGTTCATGGTCCACAATGCTTTGTTAATGTAGAGGCTACCTGCTATCCGTGGCTCCTACAGCGTTGGTTAATCTAGCCTAACGAGAAGAATGAACCCCCGCCACACTATTGCCCGTACCGTGAACTTCTGAATGATTGGGTATAGGGTTCTGACTTACGTGTATTCGCCACACTCGTCGGGTTCAGGTGGCCATCAAGGTTTTCGACCGCGGTAGAGTCGCCATAAGAACCGACGGACGGTTCAGGTACTAAGAAGTCACTATACCCCTCCTACCATTGCAGGTGCTTTAACTACCGCGATACGACAGTTAGGTTGTCGAAAGAGCAGTACTGTCCACAGGAATTACCTTGTCTCTGGTCATGCCTAACCCTTACGCACCGACCCGCAGTCAGACTCCTCGTCAATGCAGACAGTAAACAATTGATCCCGTCTTGCTAACAGAATACTTGAGATGTGGTGTTATCTAACGGGCAAAAAAGAGTAGACGATTAAGGGAAGCGCCTTCTACTCTTAGTATGGTGGGGACTTATCAGCAGCACGTATTAACGCCTACCCCCGTACGCACTATTAACAATAGCAACTACTGCTCTCTAGCAGAGCACTCTAAGATCCCTAACAAACAAAAGGTTCTAATTCTTGGCTCAGGTGGTGTGTTTTCAAAGTAAATAGAAACTCCGTCGAATGCGGTCTCCGTTTCCACTTGATGGCCAGGTGTTGGGTCTTACATCCACGATGGTCCCCAGGCATCAGATTGATACGAGGCAAAACAATGGCACTTGGTAGGCGACTTATGTTAGTTGCCGCTCCAGCCGGACCTAGTTGACTGGGTTTCGTCCGAAATGGCTGCTCCCCGCCCTGGGCGCCGCAGTCAGCCGAGGGTACAACCCGGTATGAGGAGGTATGTAGTGTGGAACGAGATGACCATCCTATGTCGCACCCTGTTTGTCCCCTACTGTGGGGTCCCTATTCCGCGCGTTGCCATCTGAATTAGAGTTACCTTGCGGTGAGTCAAAATCCACAGCCATATGTCGTACGTGCTCTCAAATCTGAGTCCCAATTTGCCTTATTTAAGATAGGGGGTGATCTCCAACAGGGGTGTACCCGTTCGAACCCACGCGAATAAAATGCTATACTTGATACGTTGGTTGACCATCTGCGAGGGGCTTACTGCGCCGGATTGCGCTCCTGAGCTGCGCTGTTACGCTACACCTCCCTTTCACGGGTGACTGAAAGGAGAGAATCAGTTTAAACTAGCCACCAGCAGGCTTTGCGTTCGGGTCGGCACTTCAGTATCGTATAAGCTGAAGCTATCATATAGTCCCGGACGCGCCCATTGCTTTACTTTGCGCTGGTTCACACTTCAACGGGACCTTGTTTCTGCCACCGGGCATACCATTAGACTCCAACTTCGTTTCCGGTGGCACCTGGAGGGGCAAAAACAATATAACATCCTTGAAGCCACGTCCGTGCCCATAAGCTGTGTTGGTTTTATTAAGTGCAAACAATTACGATGCGGTCGTATGTTGAGCGGTTGTGATAGCTGCTATTGAGGTGTAGACGGCCCTAATTCTAGTATGTACACGCTTCGCTTAGCCATTGATTACCGGAAGGGACAGTCACAAGTCGTCGGGGAATGCTACGTCCTTATGGCGTTGTCAACGTTTCCGCCTTCGCTATCTTCTCTAGTAACCAGACAATAAAGAATTTGTCCTTCCCATTAGAGGAGTTTTCCGGGTTGGTTGTTGGGCGTCTCCTGATCGATTCCGGGCAGACCACAATTGTGCGCAGGTTAACTCCGCACTCGAGGAAGATGATGGTGCTCATTAGTTCAGTGAAAATTTAGTAACCGGTATTCCAACCGGATGATGGCGTCCATGTCTCGTTGGCCTTCTGCCGGCATGCTAGTTACCTGCCCTTTGGTTGTTCTCTCTCTGCATGATCGAGCCAGCGGACCGCAATTTTCTAGACCGAAATGGCGAAAGAGTACCATAAGGACGTGTACCGTCTGGTCCTAAAAGTTCTGCGGCCGGGAAATACCACCGCCCGACAGGTTATATGGATAGTTGTCCATGAAACGCACTTATGAACGAGGGTGCGTTACAGAAGAGAGCTTGGCCTTCCATAATAAATTCTATATCTGGTTTGTCGTCGTACGCCAACCTAACGGAGTGGGTGGCTACTTTTATACTACGCCGGGCAAGGAACGTGGTCATGGTCAGAAGGAAACCGCTCCACCAGAATTCGAAAATGGGGCCTGGTCTGCCGCCTCATATGGTCGATTGTCCACGGGGGGCCTCTGTCAGGCTAGTCAGAAATGAAGTAACAAGCATCTGCACACATCTCGACTGAAATCCGAGGCGATGTGTCGTATACGGTGCCACTGCCCACCGACGTGACGATTGTTGAAACCGCAGCTAGAAGACCATTCAGGTCTTGTACTCCGTGAGATTCACCACATCCCCCCAGGCCTAGTACGCGTCCCGAGGCACATTTTGGTGTTTTGCAGCTACTGAACGAGATTTATGTTCCACGGACCGCAATGTTTTGTCAACGTACGTATGTTCGATCAAACCTGCTTTTGTAGGCGGCCACGAGAACTAAGCTAAGGATGTACAGTGGACTCGAGTCCCATGGCCCCCAATGTTTTGTCAATGTAGGTCCGTCCGATGCTCGTCCAGGTATGTACTGGGTGCAGCATAATTCGTGAGGCTCCATTACTCAACCACGGATACGGATAAAGCTCGGGCGAGGCCAACAAAAATTAGAGTAGAGCCGTGTATACTTTAAATAGAGTTTACAGCCGTGCGCTGCGCTAAGGCCTGCAAGAAGAGTCGAGCCCCATACAATCAGTAGAATGCCACTCGCTGATGGGGGTTGCTTGTCTCTGTCCAGGTACCGCCGACAGACTACACGTATTAGCCTGTTGACTGTGCACAGCTTGTCAGTCGAGTTTCCGTGGCGCCGGCATTCGTGCACGTCACCCGCCCCGGTCAGGTGCTACTGATTGCGGGACCGTTGCTTTCATAGGAATGGGGTGATCACTTTGTATAATCTTCGAGTCCTATAATAGAAGTTCGAACCATGACAAACGCAGAATGCCCTCTCTGGAGGCCGTGCGTCACAAGCTCGGCTCCTTCGGTTCTTTCGTTCCCGTCATGGGCCACAGTGCTTTGTGAATGTTTGGTATCCCCACTAACTGCCAGAGACAGCCCATACTCGGGTACTCTGCGCCGTACGTTTCCACGGCCCACAATGTTTCGTGAACGTTTCCGGGATGCGCCACGTTGTATGGAGAACTGCTGATTGAACGTTCGATAGGATACCTGACGGCCCACCTACGCACTTACGTGATATGTGATGTTCAAACGATCCACAACCTCCATTACTGCCCGTTCTTATCGAACTGGATTGTTAAGACCACAGGTGAGCCGCCGGATGAATTAGACGCCACACAGAAGTATTCTCTCAGGTAGATTGGTCGCAAACGACCAAGTATATCGTGGCTTATCGCCCGTGCCAGAGGGGAAGATGTAGTTAATGATTCTAGGTCCACGTGGACATTGACAAAACACTGAGGTCCATGCGCGAGCCTGTCTCTTATCCCTTCGAAAAGCAATCCGTCTTATAGGCCACCCAGTGGCTTTAACCCTAACTCCAGTATCGTCCTGCTACGTATATAAACCGAGGAAGTCACAGCGAAAACCGAAGGGTGCTTCTTTTTACTCGTGCTAATCCGTAAGAATAACGCTTAGGTGTAAGGGTCAAAAAAGATTCAGGCATTCAAGCGTGCAACTCTTGTACGGACTACGGTCACACCCGATGGATAATGATCCGTCCGGTCCACTATCACCCGCACATCCACAGGGGTATGTATGGGACTAATTCTCTATGCCCGAGCTATCCGCAGGCAGCGACGAATGAATTATCACTAAGTGAGCCAACTGCTGCGCACCGTTGCTAGCTATGCCCGCCTCTGAGAAACCTTTATACAATTGTAGCACACAGATAGTACGCCGTGTGCTTCAAAGCGCGCTGGTACCACATCTAATACAGTCGGAATTAAGAGGGGTCGTCAAGGAATGCACTGCGGAGGGCTTAACACCCGGGCAACCGCACATCAACCCTCACCTGGAGAGGTTCATGAGGCCCAAGCTAGTGCTCGGTAGAGAGCACCTTAAGATGGACGCTAGTTTCGCATCTTGCTTCACAATAAGGGCGACGTATTCTCTTAACTTTGGGCCCAGGTGGTCCGGGGCCAGTCTCCCACTATACTCGCAACAAGCTACAGGTATGGGCGTTCGGCAGCCTCATCATCGATTCACGTGAGTCGGTATTCAATTCGATTGGAGGGCCATGGACCGCAATGTTTCGTGAATGTCACCCGTACGATTCGTCACCCCTACCGGATGCTGGCTACTACGGTATGTACATTTTATAGGGCTTCTCATAGCCAATGTCGACAAGGTTCATTATAAAAATAACCATTCTAAACATCTGACTATTGCCCTGCAGGCGACATTGACAAAACATTGAGGACCGTGACGGGCCTCAATGTTTCGTTAACGTT"

peptide = "HGPQCFVNV"


# -----------------------------
# Peptide Encoding
# -----------------------------
encodings = String[]

window_len = 3 * length(peptide)
n = length(dna)

@inbounds for i in 1:(n - window_len + 1)
    dna_slice = dna[i:i + window_len - 1]

    # Translate both strands
    protein_fwd = translate_dna(dna_slice)
    protein_rc = translate_dna(reverse_complement(dna_slice))

    if protein_fwd == peptide || protein_rc == peptide
        push!(encodings, dna_slice)
    end
end

# -----------------------------
# Print & Save Output
# -----------------------------
println(join(encodings, "\n"))
